// Run explicitly against DATABASE_URL. Fixtures use a newly created, isolated workspace and are removed in finally.
import 'dotenv/config';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import http from 'node:http';
import { PrismaClient } from '@prisma/client';
import { io } from '../../front/node_modules/socket.io-client/build/esm/index.js';
import { createApp } from '../dist/src/app.js';
import { initializeRealtime } from '../dist/src/services/realtime.service.js';
import { createDefaultRoles, createDefaultBoard } from '../dist/src/services/workspace-bootstrap.service.js';
import { createSession } from '../dist/src/services/auth.service.js';
import { signAccessToken, hashPassword, hashToken, generateOpaqueToken } from '../dist/src/utils/crypto.js';
const p=new PrismaClient(); const wsId=crypto.randomUUID(); const users=[]; const sockets=[];
const server=http.createServer(createApp()); initializeRealtime(server); await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)); const origin=`http://127.0.0.1:${server.address().port}`;
let checks=0;
async function request(user,path,method='GET',body,expected=200){const response=await fetch(`${origin}/api/v1${path}`,{method,headers:{Authorization:`Bearer ${signAccessToken(user.id)}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json().catch(()=>({}));assert.equal(response.status,expected,`${method} ${path}: ${JSON.stringify(data)}`);checks++;return data;}
try {
 const fixture=await p.$transaction(async tx=>{
  await tx.workspace.create({data:{id:wsId,name:'QA isolated',slug:`qa-${wsId}`}});
  const roles=await createDefaultRoles(tx,wsId);
  const a=await tx.area.create({data:{workspaceId:wsId,name:'Area A'}});const b=await tx.area.create({data:{workspaceId:wsId,name:'Area B'}});
  async function person(name,role,area,userType='INTERNAL'){const u=await tx.user.create({data:{name,email:`${name}-${wsId}@example.test`}});users.push(u.id);await tx.workspaceMember.create({data:{workspaceId:wsId,userId:u.id,areaId:area.id,roleId:roles.get(role).id,status:'ACTIVE',userType,joinedAt:new Date(Date.now()-1000)}});return u;}
  const admin=await person('admin','Admin',a); const coord=await person('coord','Coordinador',a), managerA=await person('managerA','Gerente',a), managerB=await person('managerB','Gerente',b), worker=await person('worker','Colaborador',a), lender=await person('lender','Colaborador',b), reader=await person('reader','Solo lectura',a), external=await person('external','Invitado externo',a,'EXTERNAL');
  const project=await tx.project.create({data:{workspaceId:wsId,name:'QA public',areaId:a.id,visibility:'WORKSPACE',members:{create:[coord,worker,reader,external].map(u=>({userId:u.id}))}}});
  const privateProject=await tx.project.create({data:{workspaceId:wsId,name:'QA private',areaId:a.id,visibility:'PRIVATE'}});
  const other=await tx.project.create({data:{workspaceId:wsId,name:'Other area',areaId:b.id,visibility:'WORKSPACE'}});
  const board=await createDefaultBoard(tx,wsId,project.id);const statuses=await tx.boardStatus.findMany({where:{boardId:board.id}});
  return {a,b,admin,coord,managerA,managerB,worker,lender,reader,external,project,privateProject,other,board,statuses,roles};
 },{timeout:30000});
 const f=fixture, todo=f.statuses.find(s=>s.isDefault), done=f.statuses.find(s=>s.countsAsDone), active=f.statuses.find(s=>s.category==='IN_PROGRESS');

 await request(f.admin, '/auth/workspaces', 'GET', undefined, 403);
 await request(f.admin, '/auth/request-access', 'POST', {}, 403);
 await request(f.worker, `/workspaces/${wsId}/roles/catalog`, 'GET', undefined, 403);
 await request(f.managerA, `/workspaces/${wsId}/roles`, 'POST', {name:'Invalid management role',description:'Must not be created',profileId:'manager'}, 403);
 await request(f.external, `/workspaces/${wsId}/roles/catalog`, 'GET', undefined, 403);
 const catalog = await request(f.admin, `/workspaces/${wsId}/roles/catalog`); assert.equal(catalog.profiles.length,4); checks++;
 await request(f.admin, `/workspaces/${wsId}/roles`, 'POST', {name:'Admin',description:'Reserved name protection',profileId:'contributor'},409);
 await request(f.admin, `/workspaces/${wsId}/roles`, 'POST', {name:'Unsafe custom role',description:'Reject arbitrary privileges',profileId:'contributor',permissions:['workspace.manage']},400);
 const custom = (await request(f.admin, `/workspaces/${wsId}/roles`, 'POST', {name:'QA support',description:'Works on assigned support tasks',profileId:'contributor'},201)).role;
 await request(f.admin, `/workspaces/${wsId}/roles`, 'POST', {name:'qa SUPPORT',description:'Duplicate name must be rejected',profileId:'reader'},409);
 await request(f.admin, `/workspaces/${wsId}/roles/${f.roles.get('Colaborador').id}`, 'PATCH', {name:'Changed builtin',description:'Cannot change a system profile',expectedUpdatedAt:f.roles.get('Colaborador').updatedAt},403);
 await request(f.admin, `/workspaces/${wsId}/roles/${custom.id}`, 'PATCH', {name:'QA support',description:'Attempt to mutate access profile',expectedUpdatedAt:custom.updatedAt,profileId:'manager'},400);
 const renamed=(await request(f.admin, `/workspaces/${wsId}/roles/${custom.id}`, 'PATCH', {name:'QA support team',description:'Handles assigned support work',expectedUpdatedAt:custom.updatedAt})).role;
 await request(f.admin, `/workspaces/${wsId}/roles/${custom.id}`, 'PATCH', {name:'Stale edit',description:'Outdated version must not overwrite',expectedUpdatedAt:custom.updatedAt},409);
 const workerMember = await p.workspaceMember.findUnique({where:{workspaceId_userId:{workspaceId:wsId,userId:f.worker.id}}});
 const customMember = await request(f.admin, `/workspaces/${wsId}/members/${workerMember.id}`, 'PATCH', {roleId:custom.id,areaId:f.a.id,localityIds:[],positionId:null,expectedUpdatedAt:workerMember.updatedAt});
 assert.equal(customMember.member.roleId,custom.id); checks++;
 await request(f.admin, `/workspaces/${wsId}/roles/${custom.id}`, 'DELETE', undefined,409);
 await request(f.admin, `/workspaces/${wsId}/members/${workerMember.id}`, 'PATCH', {roleId:f.roles.get('Colaborador').id,areaId:f.a.id,localityIds:[],positionId:null,expectedUpdatedAt:workerMember.updatedAt},409);
 await request(f.admin, `/workspaces/${wsId}/members/${workerMember.id}`, 'PATCH', {roleId:f.roles.get('Colaborador').id,areaId:f.a.id,localityIds:[],positionId:null,expectedUpdatedAt:customMember.member.updatedAt});
 await request(f.admin, `/workspaces/${wsId}/roles/${custom.id}`, 'DELETE', undefined,204);
 await request(f.admin, `/workspaces/${wsId}/invitations`, 'POST', {email:`unscoped-${wsId}@example.test`,userType:'EXTERNAL',roleId:f.roles.get('Invitado externo').id,areaId:f.a.id},400);
 const originalProject = (await request(f.coord, `/projects/${f.project.id}`)).project;
 const plannedProject=(await request(f.coord, `/projects/${f.project.id}`, 'PATCH', {startDate:'2026-10-01T00:00:00.000Z',endDate:'2026-10-10T00:00:00.000Z',expectedUpdatedAt:originalProject.updatedAt})).project;
 await request(f.coord, `/projects/${f.project.id}`, 'PATCH', {endDate:'2026-09-01T00:00:00.000Z'},400);
 await request(f.coord, `/projects/${f.project.id}`, 'PATCH', {name:'Stale project edit',expectedUpdatedAt:originalProject.updatedAt},409);
 const clearedProject=(await request(f.coord, `/projects/${f.project.id}`, 'PATCH', {startDate:null,endDate:null,localityId:null,expectedUpdatedAt:plannedProject.updatedAt})).project;
 const persistedPlan=await p.project.findUnique({where:{id:f.project.id}}); assert.equal(persistedPlan.startDate,null); assert.equal(persistedPlan.endDate,null); checks++;

 const areaCreated=(await request(f.admin, `/workspaces/${wsId}/areas`, 'POST', {name:'QA edit area',description:'Initial area description'},201)).area;
 await request(f.admin, `/workspaces/${wsId}/areas`, 'POST', {name:'QA edit area',description:'Must not overwrite'},409);
 const areaEdited=(await request(f.admin, `/workspaces/${wsId}/organization/areas/${areaCreated.id}`, 'PATCH', {name:'QA renamed area',description:'Updated area purpose',expectedUpdatedAt:areaCreated.updatedAt})).record;
 await request(f.admin, `/workspaces/${wsId}/organization/areas/${areaCreated.id}`, 'PATCH', {name:'Stale area',description:'Cannot overwrite',expectedUpdatedAt:areaCreated.updatedAt},409);
 const positionCreated=(await request(f.managerB, `/workspaces/${wsId}/positions`, 'POST', {name:'QA operator',areaId:f.b.id},201)).position;
 await request(f.managerA, `/workspaces/${wsId}/organization/positions/${positionCreated.id}`, 'PATCH', {name:'Wrong scope',description:'Other area must remain private',expectedUpdatedAt:positionCreated.updatedAt},403);
 await request(f.external, `/workspaces/${wsId}/areas`, 'GET', undefined,403);
 await request(f.external, `/workspaces/${wsId}/invitations`, 'GET', undefined,403);
 const invitation=(await request(f.admin, `/workspaces/${wsId}/invitations`, 'POST', {email:`invite-${wsId}@example.test`,areaId:f.a.id,roleId:f.roles.get('Colaborador').id,userType:'INTERNAL'},201)).invitation;
 const invitations = await request(f.admin, `/workspaces/${wsId}/invitations`); assert.ok(invitations.invitations.some(item=>item.id===invitation.id)); assert.ok(invitations.invitations.every(item=>!('tokenHash' in item))); checks++;
 await request(f.managerB, `/workspaces/${wsId}/invitations/${invitation.id}/revoke`, 'PATCH', undefined,403);
 await request(f.admin, `/workspaces/${wsId}/invitations/${invitation.id}/revoke`, 'PATCH', undefined,204);
 await request(f.admin, `/workspaces/${wsId}/invitations/${invitation.id}/revoke`, 'PATCH', undefined,409);
 await request(f.admin, `/workspaces/${wsId}/invitations`, 'POST', {email:f.worker.email,areaId:f.a.id,roleId:f.roles.get('Colaborador').id,userType:'INTERNAL'},409);
 const limitedLocality = await p.locality.create({data:{workspaceId:wsId,areaId:f.a.id,name:'QA locality',code:'QAL'}});
 await p.workspaceMember.update({where:{workspaceId_userId:{workspaceId:wsId,userId:f.managerA.id}},data:{localityId:limitedLocality.id}});
 await request(f.managerA, `/workspaces/${wsId}/invitations`, 'POST', {email:`unscoped-manager-${wsId}@example.test`,areaId:f.a.id,localityIds:[],roleId:f.roles.get('Colaborador').id,userType:'INTERNAL'},403);
 await p.workspaceMember.update({where:{workspaceId_userId:{workspaceId:wsId,userId:f.managerA.id}},data:{localityId:null}});
 const fixturePassword = 'Integration-password-only';
 await p.user.update({where:{id:f.worker.id},data:{passwordHash:await hashPassword(fixturePassword)}});
 const inviteToken=generateOpaqueToken();
 await p.invitation.create({data:{workspaceId:wsId,invitedById:f.managerA.id,email:f.worker.email,roleId:f.roles.get('Colaborador').id,areaId:f.a.id,userType:'INTERNAL',tokenHash:hashToken(inviteToken),expiresAt:new Date(Date.now()+86400000)}});
 await request(f.worker,'/auth/accept-invitation','POST',{token:inviteToken,password:'wrong-password'},401);
 await request(f.worker,'/auth/accept-invitation','POST',{token:inviteToken,password:fixturePassword},409);
 const sessionTokens=await createSession(f.worker.id,{ip:'127.0.0.1',socket:{remoteAddress:'127.0.0.1'},header:()=> 'integration'});
 await request(f.worker,'/auth/refresh','POST',{refreshToken:sessionTokens.refreshToken});
 await request(f.worker,'/auth/refresh','POST',{refreshToken:sessionTokens.refreshToken},401);
 const visible=await request(f.managerA,`/projects?workspaceId=${wsId}`);assert.deepEqual(visible.projects.map(p=>p.id),[f.project.id]);checks++;
 await request(f.managerA,`/projects/${f.other.id}`,'GET',undefined,403);await request(f.managerA,`/projects/${f.privateProject.id}`,'GET',undefined,403);
 await request(f.external,`/staffing-requests?workspaceId=${wsId}`,'GET',undefined,403);
 await request(f.coord,`/projects/${f.project.id}/members`,'POST',{userId:f.lender.id},403);
 const created=await request(f.coord,`/boards/${f.board.id}/tasks`,'POST',{title:'Integration task',assigneeIds:[f.worker.id,f.reader.id,f.external.id]},201);const task=created.task;
 await request(f.coord,`/boards/${f.board.id}/tasks`,'POST',{title:'Hidden from worker'},201);
 const myWork=await request(f.worker,`/workspaces/${wsId}/work-items`); assert.deepEqual(myWork.tasks.map(item=>item.id),[task.id]); checks++;
 const externalWork=await request(f.external,`/workspaces/${wsId}/work-items?mine=false`); assert.deepEqual(externalWork.tasks.map(item=>item.id),[task.id]); checks++;
 const otherAreaWork=await request(f.managerB,`/workspaces/${wsId}/work-items?mine=false`); assert.equal(otherAreaWork.total,0); checks++;
 const paginatedWork=await request(f.coord,`/workspaces/${wsId}/work-items?mine=false&limit=1`); assert.equal(paginatedWork.total,2); assert.equal(paginatedWork.tasks.length,1); assert.equal(paginatedWork.pages,2); checks++;
 const emptySearch=await request(f.coord,`/workspaces/${wsId}/work-items?mine=false&search=does-not-exist`); assert.equal(emptySearch.total,0); checks++;
 await request(f.coord,`/workspaces/${wsId}/work-items?page=0`,'GET',undefined,400);
 const workerTasks=await request(f.worker,`/boards/${f.board.id}/tasks`);assert.deepEqual(workerTasks.tasks.map(t=>t.id),[task.id]);checks++;
 await request(f.reader,`/tasks/${task.id}/status`,'PATCH',{statusId:active.id},403);
 await request(f.worker,`/tasks/${task.id}/status`,'PATCH',{statusId:done.id},403);
 await request(f.worker,`/tasks/${task.id}`,'PATCH',{title:'Forbidden'},403);
 await request(f.worker,`/tasks/${task.id}`,'PATCH',{progress:25});
 await request(f.coord,`/tasks/${task.id}`,'PATCH',{title:'Conflict',expectedUpdatedAt:task.updatedAt},409);
 const updated=await request(f.coord,`/tasks/${task.id}`,'PATCH',{dueAt:'2026-10-01T00:00:00.000Z'});
 await request(f.coord,`/tasks/${task.id}`,'PATCH',{startAt:'2026-10-02T00:00:00.000Z'},400);
 await request(f.coord,`/tasks/${task.id}`,'PATCH',{clearFields:['dueAt'],expectedUpdatedAt:updated.task.updatedAt});
 const child=await request(f.coord,`/boards/${f.board.id}/tasks`,'POST',{title:'Open child',parentTaskId:task.id,assigneeIds:[f.worker.id]},201);
 await request(f.coord,`/tasks/${task.id}/status`,'PATCH',{statusId:done.id},409);
 await request(f.coord,`/tasks/${child.task.id}/status`,'PATCH',{statusId:done.id});
 await request(f.coord,`/tasks/${task.id}/status`,'PATCH',{statusId:done.id});
 const completedWork=await request(f.worker,`/workspaces/${wsId}/work-items?state=completed&mine=false`); assert.equal(completedWork.total,2); checks++;
 const wrongDates=await request(f.worker,`/workspaces/${wsId}/work-items?state=completed&completedFrom=2000-01-01T00:00:00.000Z&completedTo=2001-01-01T00:00:00.000Z`); assert.equal(wrongDates.total,0); checks++;
 await request(f.worker,`/tasks/${task.id}/comments`,'POST',{body:'Locked'},403);
 await request(f.coord,`/tasks/${task.id}/status`,'PATCH',{statusId:todo.id});
 await request(f.external,`/tasks/${task.id}/comments`,'POST',{body:'Secret',isInternal:true},403);
 await request(f.coord,`/tasks/${task.id}/comments`,'POST',{body:'Internal note',isInternal:true},201);
 const comments=await request(f.external,`/tasks/${task.id}/comments`);assert.equal(comments.comments.length,0);checks++;
 const staffing=await request(f.coord,'/staffing-requests','POST',{projectId:f.project.id,targetAreaId:f.b.id,quantity:1,note:'Integration staffing'},201);
 await request(f.managerA,`/staffing-requests/${staffing.staffingRequest.id}/approve`,'PATCH',{approvedUserIds:[f.lender.id]},403);
 await request(f.managerB,`/staffing-requests/${staffing.staffingRequest.id}/approve`,'PATCH',{approvedUserIds:[f.worker.id]},400);
 await request(f.managerB,`/staffing-requests/${staffing.staffingRequest.id}/approve`,'PATCH',{approvedUserIds:[f.lender.id]});
 await request(f.managerB,`/staffing-requests/${staffing.staffingRequest.id}/approve`,'PATCH',{approvedUserIds:[f.lender.id]},409);
 const membership=await p.projectMember.findUnique({where:{projectId_userId:{projectId:f.project.id,userId:f.lender.id}}});assert.equal(membership.roleId,null);checks++;
 const inbox=await request(f.worker,`/notifications?workspaceId=${wsId}`);assert.ok(inbox.unreadCount>0);assert.ok(inbox.notifications?.length || inbox.items?.length);checks++;
 const item=(inbox.items??inbox.notifications)[0];await request(f.worker,'/notifications/read','POST',{workspaceId:wsId,ids:[item.id]});
 const readAgain=await request(f.worker,`/notifications?workspaceId=${wsId}`);assert.equal(readAgain.unreadCount,inbox.unreadCount-1);checks++;
 const externalInbox=await request(f.external,`/notifications?workspaceId=${wsId}`);assert.equal((externalInbox.items??externalInbox.notifications).some(i=>i.title==='Nuevo comentario'),false);checks++;
 const socket=io(origin,{auth:{token:signAccessToken(f.worker.id)},transports:['websocket'],reconnection:false});sockets.push(socket);
 await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('socket connect timeout')),5000);socket.once('connect',()=>{clearTimeout(timeout);resolve()});socket.once('connect_error',reject)});
 const ack=await socket.timeout(5000).emitWithAck('workspace:join',{workspaceId:wsId});assert.equal(ack.ok,true);checks++;
 const eventPromise=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('socket event timeout')),15000);socket.on('realtime:event',e=>{if(e.taskId===task.id&&e.type==='task.updated'){clearTimeout(timer);resolve(e)}})});
 eventPromise.catch(()=>{});
 await request(f.coord,`/tasks/${task.id}`,'PATCH',{title:'Changed over socket'});await eventPromise;checks++;
 await p.workspaceMember.update({where:{workspaceId_userId:{workspaceId:wsId,userId:f.worker.id}},data:{status:'SUSPENDED'}});
 await request(f.worker,`/boards/${f.board.id}/tasks`,'GET',undefined,403);
 const denied=await socket.timeout(5000).emitWithAck('task:join',{taskId:task.id});assert.equal(denied.ok,false);checks++;
 console.log(`PASS: ${checks} comprobaciones de API, permisos, concurrencia, colaboración, bandeja y socket.`);
} finally {
 for(const socket of sockets) socket.disconnect();
 server.closeAllConnections(); await new Promise(resolve=>server.close(resolve));
 // Only records in the fresh test workspace are eligible for cleanup.
 const taskWhere={workspaceId:wsId}; const taskRelation={task:taskWhere};
 await p.$transaction(async tx=>{
  await tx.session.deleteMany({where:{userId:{in:users}}});
  await tx.invitationLocality.deleteMany({where:{invitation:{workspaceId:wsId}}});await tx.invitation.deleteMany({where:{workspaceId:wsId}});
  await tx.notificationRead.deleteMany({where:{activity:{workspaceId:wsId}}});await tx.activityLog.deleteMany({where:{workspaceId:wsId}});
  await tx.projectStaffingAssignment.deleteMany({where:{request:{workspaceId:wsId}}});await tx.projectStaffingRequest.deleteMany({where:{workspaceId:wsId}});
  await tx.comment.deleteMany({where:taskRelation});await tx.timeLog.deleteMany({where:taskRelation});await tx.taskAssignee.deleteMany({where:taskRelation});await tx.taskMention.deleteMany({where:taskRelation});
  await tx.task.deleteMany({where:{...taskWhere,parentTaskId:{not:null}}});await tx.task.deleteMany({where:taskWhere});
  await tx.boardStatus.deleteMany({where:{board:{workspaceId:wsId}}});await tx.board.deleteMany({where:{workspaceId:wsId}});await tx.projectMember.deleteMany({where:{project:{workspaceId:wsId}}});await tx.project.deleteMany({where:{workspaceId:wsId}});
  await tx.workspaceMemberLocality.deleteMany({where:{workspaceMember:{workspaceId:wsId}}});await tx.workspaceMember.deleteMany({where:{workspaceId:wsId}});
  await tx.rolePermission.deleteMany({where:{role:{workspaceId:wsId}}});await tx.role.deleteMany({where:{workspaceId:wsId}});await tx.permission.deleteMany({where:{workspaceId:wsId}});
  await tx.position.deleteMany({where:{workspaceId:wsId}});await tx.locality.deleteMany({where:{workspaceId:wsId}});await tx.area.deleteMany({where:{workspaceId:wsId}});await tx.workspace.deleteMany({where:{id:wsId}});await tx.user.deleteMany({where:{id:{in:users}}});
 },{timeout:30000});await p.$disconnect();
}
