import type { ViewKey } from '../types';
import { Dialog } from './ui/Dialog';
const guides: Record<ViewKey, { title: string; purpose: string; steps: string[] }> = {
  work: { title: 'Mi trabajo', purpose: 'Todas tus tareas pendientes en un solo lugar.', steps: ['Abre una tarea para ver su descripción, responsables y entrega.', 'Actualiza el avance o abre Mensajes para conversar con el equipo.', 'Cuando termines, pásala a revisión. La coordinación valida y cierra.'] },
  notifications: { title: 'Notificaciones', purpose: 'Cada aviso te lleva al trabajo que requiere atención.', steps: ['Filtra por mensajes, tareas o solicitudes. Cada aviso indica quién hizo el cambio y te lleva al detalle.', 'La lectura queda guardada para tus otros dispositivos.', 'Instala la app en tu móvil y activa avisos para recibir novedades cuando esté cerrada.'] },
  projects: { title: 'Proyectos', purpose: 'Un proyecto reúne a las personas y tareas de un objetivo.', steps: ['Crea el proyecto con un nombre, área y visibilidad.', 'Usa Crear tarea para asignar personas del área; se incorporan al proyecto al guardar.', 'Crea una tarea, asigna responsables y define la entrega.'] },
  board: { title: 'Tablero', purpose: 'El estado indica qué sigue para cada tarea.', steps: ['Crear tarea abre un formulario para crear y asignar en el mismo paso.', 'Abre una tarjeta para editar, comentar o consultar su historial.', 'Por hacer → En proceso → En revisión → Terminado. Usa Bloqueado cuando necesites ayuda.'] },
  completed: { title: 'Terminadas', purpose: 'El historial del trabajo que coordinación ya cerró.', steps: ['Busca por tarea o responsable y filtra por proyecto.', 'El filtro de fechas usa el cierre real de la tarea.', 'Abre una tarea para ver su historial. Reabrir depende de tu rol.'] },
  management: { title: 'Solicitudes de apoyo', purpose: 'Una persona de otra área se incorpora con autorización de su responsable.', steps: ['Pedir apoyo: elige proyecto, área destino y cuántas personas necesitas.', 'El responsable del área elige las personas disponibles o explica el rechazo.', 'Al aprobar, las personas entran al proyecto con su rol actual y pueden recibir tareas.'] },
  members: { title: 'Personas', purpose: 'Cada acceso tiene un rol y un alcance explícitos.', steps: ['Invitar persona: correo, rol y área. Un externo también necesita un proyecto.', 'Copia el enlace y compártelo con la persona. Caduca en 7 días.', 'Consulta Invitaciones para ver su estado o cancelar el enlace. Editar acceso permite cambiar rol y alcance.'] },
  roles: { title: 'Roles y permisos', purpose: 'El rol define acciones; el área y la localidad definen el alcance.', steps: ['Consulta: lee. Colaborador: ejecuta sus tareas. Coordinador: organiza y revisa. Responsable de área: coordina equipos y apoyo.', 'Crear rol: elige un perfil, un nombre y su propósito. Solo administración puede hacerlo.', 'Los perfiles de acceso quedan estables. Para otro nivel, crea otro rol y reasigna a la persona desde Personas.'] },
  organization: { title: 'Organización', purpose: 'Una estructura pequeña y clara es más fácil de mantener.', steps: ['Área: el equipo responsable. Ejemplo: Operaciones.', 'Localidad: dónde trabaja ese equipo. Ejemplo: Guadalajara.', 'Puesto: la función de una persona. Ejemplo: Analista. El puesto no concede permisos.'] },
  reports: { title: 'Resumen del trabajo', purpose: 'Avances, vencimientos y bloqueos dentro de tu alcance.', steps: ['Selecciona el período que necesitas revisar.', 'Abre un proyecto o tarea para actuar sobre sus pendientes.', 'Consulta el trabajo por persona y exporta el reporte para compartirlo. El tiempo registrado no es una clasificación de desempeño.'] }
};
export function GuideDrawer({ currentView, isOpen, onClose }: { currentView: ViewKey; isOpen: boolean; onClose: () => void }) {
  if (!isOpen) return null;
  const guide = guides[currentView];
  return <Dialog title={guide.title} description={guide.purpose} onClose={onClose}><div className="product-form"><ol className="quick-guide">{guide.steps.map((step, index) => <li key={step}><span>{index + 1}</span><p>{step}</p></li>)}</ol><div className="scope-note"><strong>Cambios en tiempo real</strong><p>Las tareas, asignaciones y avisos se actualizan automáticamente. Si se pierde la conexión, la aplicación muestra «Recuperando conexión» y vuelve a sincronizar al recuperarla.</p></div></div></Dialog>;
}
