import { useState } from 'react';
import { InstallAppButton } from './InstallAppButton';
import { ArrowRight, Bell, Check, CheckCheck, MessageSquare, Smartphone, UsersRound } from 'lucide-react';
import { Button, EmptyState, LoadingState } from './ui';
import type { InboxItem, useNotificationInbox } from '../hooks/useNotificationInbox';
type Inbox = ReturnType<typeof useNotificationInbox>;
export function NotificationInbox({ inbox, onOpen, onEnable, onDisable, onRecheck, device }: { inbox: Inbox; onOpen: (item: InboxItem) => void; onEnable: () => Promise<void>; onDisable: () => Promise<void>; onRecheck: () => Promise<void>; device: {state:string;message:string} }) {
  const [error,setError]=useState('');const [saving,setSaving]=useState(false);
  const [enabling,setEnabling]=useState(false);const [deviceError,setDeviceError]=useState('');
  const deviceEnabled=device.state==='enabled';
  async function enable(){if(enabling)return;setEnabling(true);setDeviceError('');try{await onEnable();}catch(failure){setDeviceError(failure instanceof Error?failure.message:'No se pudieron activar las notificaciones.');}finally{setEnabling(false);}}
  return <section className="day-inbox"><header className="day-home-heading"><div><p className="day-kicker">Actividad que necesitas conocer</p><h1>Notificaciones</h1><p>{inbox.unreadCount?`Tienes ${inbox.unreadCount} ${inbox.unreadCount===1?'notificación sin leer':'notificaciones sin leer'}.`:'No tienes notificaciones pendientes.'} Abre un aviso para ir directamente a su tarea o conversación.</p></div><span className="day-inbox-count"><Bell size={24}/>{inbox.unreadCount}</span></header>
    <div className="day-inbox-grid"><section className="day-inbox-feed"><header><nav aria-label="Estado de lectura"><button className={!inbox.unreadOnly?'selected':''} onClick={()=>inbox.setUnreadOnly(false)}>Todas</button><button className={inbox.unreadOnly?'selected':''} onClick={()=>inbox.setUnreadOnly(true)}>Sin leer <span>{inbox.unreadCount}</span></button></nav><Button variant="ghost" size="sm" icon={<CheckCheck size={16}/>} disabled={saving||!inbox.items.some(item=>!item.readAt)} onClick={async()=>{setSaving(true);setError('');try{await inbox.markRead(inbox.items.filter(item=>!item.readAt).map(item=>item.id));}catch{setError('No se pudo guardar la lectura. Inténtalo de nuevo.');}finally{setSaving(false);}}}>{saving?'Guardando…':'Marcar visibles como leídas'}</Button></header>
    <div className="notification-filter"><label>Tipo de aviso<select value={inbox.category} onChange={event=>inbox.setCategory(event.target.value as typeof inbox.category)}><option value="all">Todos los avisos</option><option value="messages">Mensajes</option><option value="tasks">Tareas y proyectos</option><option value="requests">Solicitudes de apoyo</option></select></label><span>{inbox.total} resultados</span></div>
    {(error||inbox.error)&&<p className="form-error" role="alert">{error||'No pudimos cargar tus avisos.'}<Button onClick={()=>void inbox.refresh()}>Reintentar</Button></p>}
    {inbox.isLoading?<LoadingState label="Cargando notificaciones…" rows={4}/>:inbox.items.length?inbox.items.map(item=><button className={`day-message ${item.readAt?'read':'unread'}`} key={item.id} onClick={()=>onOpen(item)}><span className="day-message-icon">{item.category==='messages'?<MessageSquare size={18}/>:item.category==='requests'?<UsersRound size={18}/>:<Bell size={18}/>}</span><span><span className="notification-title"><strong>{item.title}</strong>{!item.readAt&&<b>Sin leer</b>}</span><p>{item.message}</p>{item.context&&<span className="notification-context">{item.context}{item.projectName&&item.context!==item.projectName&&<small>{item.projectName}</small>}</span>}<span className="notification-footer"><small>{new Date(item.createdAt).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})}</small><span>{item.actionLabel??'Ver detalle'}<ArrowRight size={14}/></span></span></span></button>):<EmptyState icon={<CheckCheck size={27}/>} title={inbox.unreadOnly?'No hay avisos sin leer con estos filtros':'No hay avisos con estos filtros'} description="Las asignaciones, mensajes y respuestas del equipo se guardan aquí automáticamente."/>}
    {inbox.total>30&&<footer className="day-list-pagination"><Button disabled={!inbox.page} onClick={()=>inbox.setPage(inbox.page-1)}>Anterior</Button><span>Página {inbox.page+1} de {Math.ceil(inbox.total/30)}</span><Button disabled={(inbox.page+1)*30>=inbox.total} onClick={()=>inbox.setPage(inbox.page+1)}>Siguiente</Button></footer>}</section>
    <aside className="day-mobile-card pwa-device-card">
      <span><Smartphone size={29}/></span><h2>Vianko en tu dispositivo</h2>
      <p>Instala la app y recibe tus avisos incluso cuando no esté abierta.</p>
      <div className="pwa-setup-step"><span>1</span><div><h3>Instala la aplicación</h3><p>Accede desde un icono en tu pantalla de inicio.</p><InstallAppButton/></div></div>
      <div className="pwa-setup-step"><span>2</span><div><h3>Activa tus avisos</h3><p>{device.message || 'Consultando la configuración del dispositivo…'}</p>
        <Button variant="primary" disabled={enabling || deviceEnabled || ['checking','unsupported','server-missing'].includes(device.state)} onClick={()=>void enable()}>{deviceEnabled?<Check size={16}/>:<Bell size={16}/>} {enabling?'Guardando…':deviceEnabled?'Avisos activados':'Activar avisos'}</Button>
        {deviceEnabled && <Button variant="ghost" disabled={enabling} onClick={async()=>{setEnabling(true);setDeviceError('');try{await onDisable();}catch{setDeviceError('No se pudo desactivar. Inténtalo otra vez.');}finally{setEnabling(false);}}}>Desactivar en este dispositivo</Button>}
        {['unavailable','server-missing','denied'].includes(device.state) && <Button disabled={enabling} onClick={async()=>{setEnabling(true);setDeviceError('');try{await onRecheck();}finally{setEnabling(false);}}}>Volver a comprobar</Button>}
      </div></div>
      {deviceError&&<p className="form-error" role="alert">{deviceError}</p>}
      <p className="pwa-device-note">Los permisos se configuran por dispositivo. En iPhone, abre primero la app instalada desde su icono.</p>
    </aside></div>
  </section>;
}
