import { useState } from 'react';
import { ArrowRight, Bell, Check, CheckCheck, MessageSquare, Smartphone, UsersRound } from 'lucide-react';
import { Button, EmptyState, LoadingState } from './ui';
import type { InboxItem, useNotificationInbox } from '../hooks/useNotificationInbox';
type Inbox = ReturnType<typeof useNotificationInbox>;
export function NotificationInbox({ inbox, onOpen, onEnable }: { inbox: Inbox; onOpen: (item: InboxItem) => void; onEnable: () => Promise<void> }) {
  const [error,setError]=useState('');const [saving,setSaving]=useState(false);
  const [enabling,setEnabling]=useState(false);const [deviceEnabled,setDeviceEnabled]=useState(false);const [deviceError,setDeviceError]=useState('');
  async function enable(){if(enabling)return;setEnabling(true);setDeviceError('');try{await onEnable();setDeviceEnabled(true);}catch(failure){setDeviceError(failure instanceof Error?failure.message:'No se pudieron activar las notificaciones.');}finally{setEnabling(false);}}
  return <section className="day-inbox"><header className="day-home-heading"><div><p className="day-kicker">Actividad que necesitas conocer</p><h1>Notificaciones</h1><p>{inbox.unreadCount?`Tienes ${inbox.unreadCount} ${inbox.unreadCount===1?'notificación sin leer':'notificaciones sin leer'}.`:'No tienes notificaciones pendientes.'} Abre un aviso para ir directamente a su tarea o conversación.</p></div><span className="day-inbox-count"><Bell size={24}/>{inbox.unreadCount}</span></header>
    <div className="day-inbox-grid"><section className="day-inbox-feed"><header><nav aria-label="Estado de lectura"><button className={!inbox.unreadOnly?'selected':''} onClick={()=>inbox.setUnreadOnly(false)}>Todas</button><button className={inbox.unreadOnly?'selected':''} onClick={()=>inbox.setUnreadOnly(true)}>Sin leer <span>{inbox.unreadCount}</span></button></nav><Button variant="ghost" size="sm" icon={<CheckCheck size={16}/>} disabled={saving||!inbox.items.some(item=>!item.readAt)} onClick={async()=>{setSaving(true);setError('');try{await inbox.markRead(inbox.items.filter(item=>!item.readAt).map(item=>item.id));}catch{setError('No se pudo guardar la lectura. Inténtalo de nuevo.');}finally{setSaving(false);}}}>{saving?'Guardando…':'Marcar visibles como leídas'}</Button></header>
    <div className="notification-filter"><label>Tipo de aviso<select value={inbox.category} onChange={event=>inbox.setCategory(event.target.value as typeof inbox.category)}><option value="all">Todos los avisos</option><option value="messages">Mensajes</option><option value="tasks">Tareas y proyectos</option><option value="requests">Solicitudes de apoyo</option></select></label><span>{inbox.total} resultados</span></div>
    {(error||inbox.error)&&<p className="form-error" role="alert">{error||'No pudimos cargar tus avisos.'}<Button onClick={()=>void inbox.refresh()}>Reintentar</Button></p>}
    {inbox.isLoading?<LoadingState label="Cargando notificaciones…" rows={4}/>:inbox.items.length?inbox.items.map(item=><button className={`day-message ${item.readAt?'read':'unread'}`} key={item.id} onClick={()=>onOpen(item)}><span className="day-message-icon">{item.category==='messages'?<MessageSquare size={18}/>:item.category==='requests'?<UsersRound size={18}/>:<Bell size={18}/>}</span><span><span className="notification-title"><strong>{item.title}</strong>{!item.readAt&&<b>Sin leer</b>}</span><p>{item.message}</p>{item.context&&<span className="notification-context">{item.context}{item.projectName&&item.context!==item.projectName&&<small>{item.projectName}</small>}</span>}<span className="notification-footer"><small>{new Date(item.createdAt).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})}</small><span>{item.actionLabel??'Ver detalle'}<ArrowRight size={14}/></span></span></span></button>):<EmptyState icon={<CheckCheck size={27}/>} title={inbox.unreadOnly?'No hay avisos sin leer con estos filtros':'No hay avisos con estos filtros'} description="Las asignaciones, mensajes y respuestas del equipo se guardan aquí automáticamente."/>}
    {inbox.total>30&&<footer className="day-list-pagination"><Button disabled={!inbox.page} onClick={()=>inbox.setPage(inbox.page-1)}>Anterior</Button><span>Página {inbox.page+1} de {Math.ceil(inbox.total/30)}</span><Button disabled={(inbox.page+1)*30>=inbox.total} onClick={()=>inbox.setPage(inbox.page+1)}>Siguiente</Button></footer>}</section>
    <aside className="day-mobile-card"><span><Smartphone size={29}/></span><h2>Avisos en tu dispositivo</h2><p>La bandeja guarda tus notificaciones. Activa también los avisos del navegador para enterarte cuando no tengas la aplicación abierta.</p><Button variant="primary" disabled={enabling||deviceEnabled} onClick={()=>void enable()}>{deviceEnabled?<Check size={16}/>:<Bell size={16}/>} {enabling?'Activando…':deviceEnabled?'Dispositivo registrado':'Activar en este dispositivo'}</Button>{deviceEnabled&&<p className="notification-device-feedback" role="status">Listo. Este dispositivo quedó registrado para recibir tus avisos.</p>}{deviceError&&<p className="form-error" role="alert">{deviceError}</p>}<div><h3>Usarla como app móvil</h3><ol><li>Abre esta dirección en el navegador de tu móvil.</li><li>Elige «Agregar a pantalla de inicio».</li><li>Abre la app instalada y activa los avisos.</li></ol><small>En iPhone, la opción está en el menú Compartir.</small></div></aside></div>
  </section>;
}
