import { useEffect, useRef, useState, type ChangeEvent, type DragEvent } from 'react';
import { useInfiniteQuery, useQuery, useQueryClient } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { ArrowDown, Check, Clock3, Download, File, LoaderCircle, MessageSquare, Paperclip, Plus, Send, ShieldCheck, Trash2, UsersRound, X } from 'lucide-react';
import { apiRequest, apiBaseUrl } from '../api/http';
import { Button } from './ui';
import { Dialog } from './ui/Dialog';
import { initials } from '../lib/format';
import type { Project } from '../types';
type ChatFile={id:string;name:string;size:number;mimeType:string;uploadedById:string};
type Message={id:string;chatId:string;clientId:string;body:string;createdAt:string;deletedAt?:string;user:{id:string;name:string};files:ChatFile[];canDelete:boolean};
type ChatContext={chat?:{id:string;createdAt:string;expiresAt:string;createdBy:{name:string}};canCreate:boolean;canWrite:boolean;canModerate:boolean;participants:{id:string;name:string}[];serverTime:string;maxFileBytes:number};
type MessagePage={messages:Message[];hasMore:boolean;expiresAt:string};
type PickedFile={id:string;file:globalThis.File;state:'waiting'|'uploading'|'ready'|'error'};
function sizeLabel(size:number){return size>=1048576?`${(size/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(size/1024))} KB`;}
async function fileResponse(response:Response){if(response.ok)return;const data=await response.json().catch(()=>undefined);throw new Error(data?.error?.message??'No se pudo transferir el archivo. Revisa tu conexión e inténtalo otra vez.');}
export function ProjectChat({token,project,currentUserId,connectionState}:{token:string;project:Project;currentUserId:string;connectionState:'live'|'connecting'|'reconnecting'}){
 const client=useQueryClient();const [params,setParams]=useSearchParams();
 const [body,setBody]=useState('');const [files,setFiles]=useState<PickedFile[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const [confirm,setConfirm]=useState<{kind:'start'|'close'|'message'|'file';id?:string;name?:string}>();
 const [now,setNow]=useState(Date.now());const [downloading,setDownloading]=useState<string>();const [nearBottom,setNearBottom]=useState(true);const [incoming,setIncoming]=useState(0);
 const [visible,setVisible]=useState(document.visibilityState==='visible');const [readRevision,setReadRevision]=useState(0);
 const pending=useRef<{clientId:string;body:string;fileIds:string[]}>();const sending=useRef(false);const fileInput=useRef<HTMLInputElement>(null);const feed=useRef<HTMLDivElement>(null);const previousIds=useRef(new Set<string>());const roomRef=useRef<string>();const readIds=useRef(new Set<string>());const readBusy=useRef(false);
 const context=useQuery({queryKey:['project-chat',project.id],queryFn:()=>apiRequest<ChatContext>(`/projects/${project.id}/chat`,{token}),refetchOnWindowFocus:true,refetchOnReconnect:true,refetchInterval:30000});
 const chat=context.data?.chat;const offset=context.data?new Date(context.data.serverTime).getTime()-context.dataUpdatedAt:0;
 const expired=Boolean(chat&&new Date(chat.expiresAt).getTime()<=now+offset);
 const linked=params.get('chat');const wrongChat=Boolean(linked&&linked!=='1'&&chat&&linked!==chat.id);
 const chatId=chat?.id;const active=Boolean(chatId&&!expired&&!wrongChat);
 const messagesQuery=useInfiniteQuery({queryKey:['chat-messages',chatId],initialPageParam:undefined as string|undefined,queryFn:({pageParam})=>apiRequest<MessagePage>(`/chats/${chatId}/messages${pageParam?`?before=${pageParam}`:''}`,{token}),getNextPageParam:page=>page.hasMore?page.messages[0]?.id:undefined,enabled:active,refetchOnWindowFocus:true,refetchOnReconnect:true,refetchInterval:connectionState==='live'?false:15000});
 const messages=Array.from(new Map((messagesQuery.data?.pages??[]).flatMap(page=>page.messages).map(message=>[message.id,message])).values()).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id));
 const latestId=messages[messages.length-1]?.id;
 const remaining=chat?Math.max(0,new Date(chat.expiresAt).getTime()-(now+offset)):0;
 const lifetime=remaining>=86400000?`${Math.ceil(remaining/86400000)} días`:remaining>=3600000?`${Math.ceil(remaining/3600000)} h`:`${Math.ceil(remaining/60000)} min`;
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),15000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{const update=()=>setVisible(document.visibilityState==='visible');document.addEventListener('visibilitychange',update);return()=>document.removeEventListener('visibilitychange',update);},[]);
 useEffect(()=>{if(roomRef.current!==chatId){roomRef.current=chatId;previousIds.current=new Set();readIds.current=new Set();setFiles([]);setBody('');pending.current=undefined;setError('');setIncoming(0);} },[chatId]);
 useEffect(()=>{if(!active)return;const unseen=messages.filter(message=>!previousIds.current.has(message.id)&&message.user.id!==currentUserId);if(!previousIds.current.size||nearBottom){if(feed.current)feed.current.scrollTop=feed.current.scrollHeight;setIncoming(0);}else if(unseen.length)setIncoming(count=>count+unseen.length);previousIds.current=new Set(messages.map(message=>message.id));},[latestId,active]);
 useEffect(()=>{
  if(!active||!chatId||!nearBottom||!visible||readBusy.current)return;
  const ids=messages.filter(message=>!readIds.current.has(message.id)&&message.user.id!==currentUserId).slice(-100).map(message=>message.id);if(!ids.length&&readIds.current.has(chatId))return;
  let succeeded=false;readBusy.current=true;void apiRequest(`/chats/${chatId}/read`,{token,method:'POST',body:{messageIds:ids}}).then(()=>{succeeded=true;if(roomRef.current===chatId){ids.forEach(id=>readIds.current.add(id));readIds.current.add(chatId);}void client.invalidateQueries({queryKey:['notifications']});}).catch(()=>undefined).finally(()=>{readBusy.current=false;if(succeeded)setReadRevision(value=>value+1);});
 },[latestId,nearBottom,active,token,visible,readRevision,now]);
 useEffect(()=>{if(expired){setFiles([]);setBody('');pending.current=undefined;client.removeQueries({queryKey:['chat-messages',chatId]});void context.refetch();}},[expired]);
 async function refresh(){await Promise.all([client.invalidateQueries({queryKey:['project-chat',project.id]}),client.invalidateQueries({queryKey:['chat-messages',chatId]})]);}
 async function executeConfirm(){if(!confirm||busy)return;setBusy(true);setError('');try{
  if(confirm.kind==='start'){const response=await apiRequest<{chat:{id:string}}>(`/projects/${project.id}/chat`,{token,method:'POST',body:{}});const next=new URLSearchParams(params);next.set('chat',response.chat.id);setParams(next,{replace:true});}
  else if(confirm.kind==='close'){await apiRequest(`/chats/${chatId}`,{token,method:'DELETE'});client.removeQueries({queryKey:['chat-messages',chatId]});setBody('');setFiles([]);pending.current=undefined;setNotice('Chat cerrado. Se eliminaron sus mensajes y archivos.');}
  else{await apiRequest(`/chats/${chatId}/${confirm.kind==='file'?'files':'messages'}/${confirm.id}`,{token,method:'DELETE'});setNotice(confirm.kind==='file'?'Archivo eliminado.':'Mensaje y sus archivos eliminados.');}
  await refresh();setConfirm(undefined);
 }catch(failure){setError(failure instanceof Error?failure.message:'No se pudo completar la acción.');}finally{setBusy(false);}}
 function pick(selected:globalThis.File[]){if(busy||pending.current)return;setError('');const accepted:PickedFile[]=[];for(const file of selected){if(files.length+accepted.length>=3){setError('Puedes adjuntar hasta tres archivos por mensaje.');break;}if(!file.size||file.size>10*1048576){setError(`«${file.name}» debe pesar entre 1 byte y 10 MB.`);continue;}accepted.push({id:crypto.randomUUID(),file,state:'waiting'});}setFiles(previous=>[...previous,...accepted]);}
 async function removePicked(id:string){const selected=files.find(file=>file.id===id);if(selected?.state==='ready'&&chatId){try{await apiRequest(`/chats/${chatId}/files/${id}?pending=true`,{token,method:'DELETE'});}catch{/* Unattached files are purged automatically. */}}setFiles(previous=>previous.filter(file=>file.id!==id));}
 async function send(){if(!active||sending.current||busy||!context.data?.canWrite||(!body.trim()&&!files.length))return;sending.current=true;setBusy(true);setError('');setNotice('');
  const packet=pending.current??{clientId:crypto.randomUUID(),body:body.trim(),fileIds:files.map(file=>file.id)};pending.current=packet;
  try{for(const selected of files){if(selected.state==='ready')continue;setFiles(previous=>previous.map(file=>file.id===selected.id?{...file,state:'uploading'}:file));
    const query=new URLSearchParams({name:selected.file.name,mimeType:selected.file.type||'application/octet-stream'});
    try{const response=await fetch(`${apiBaseUrl}/chats/${chatId}/files/${selected.id}?${query}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/octet-stream'},body:selected.file});await fileResponse(response);setFiles(previous=>previous.map(file=>file.id===selected.id?{...file,state:'ready'}:file));}
    catch(failure){setFiles(previous=>previous.map(file=>file.id===selected.id?{...file,state:'error'}:file));throw failure;}
   }
   await apiRequest(`/chats/${chatId}/messages`,{token,method:'POST',body:packet});pending.current=undefined;setBody('');setFiles([]);setNearBottom(true);await refresh();if(feed.current)feed.current.scrollTop=feed.current.scrollHeight;
  }catch(failure){setError(failure instanceof Error?failure.message:'No se pudo enviar. Tu mensaje se conserva para reintentar.');}
  finally{sending.current=false;setBusy(false);}
 }
 async function download(file:ChatFile){setDownloading(file.id);setError('');try{const response=await fetch(`${apiBaseUrl}/chats/${chatId}/files/${file.id}`,{headers:{Authorization:`Bearer ${token}`}});await fileResponse(response);const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(failure){setError(failure instanceof Error?failure.message:'No se pudo descargar el archivo.');}finally{setDownloading(undefined);}}
 function drop(event:DragEvent){event.preventDefault();if(active&&context.data?.canWrite)pick(Array.from(event.dataTransfer.files));}
 const initialError=context.error??messagesQuery.error;
 return <section className="project-chat" onDragOver={event=>{if(event.dataTransfer.types.includes('Files'))event.preventDefault();}} onDrop={drop}>
  <header className="project-chat-header"><div><span className="chat-heading-icon"><MessageSquare size={21}/></span><div><h2>Chat de seguimiento</h2><p>{active?`Disponible hasta ${new Date(chat!.expiresAt).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})}`:'Conversaciones cortas para resolver el trabajo de esta semana.'}</p></div></div><div>{active&&<span className="chat-lifetime"><Clock3 size={14}/>Vence en {lifetime}</span>}{active&&context.data?.canModerate&&<Button variant="ghost" size="sm" disabled={busy} icon={<Trash2 size={15}/>} onClick={()=>{setError('');setConfirm({kind:'close'});}}>Cerrar chat</Button>}</div></header>
  {(error||initialError)&&!confirm&&<p className="form-error" role="alert">{error||initialError?.message}{initialError&&<Button size="sm" onClick={()=>void refresh()}>Reintentar</Button>}</p>}{notice&&<p className="chat-notice" role="status"><Check size={14}/>{notice}</p>}
  {context.isLoading?<p className="chat-loading">Abriendo el chat…</p>:!active?<div className="chat-start"><span><MessageSquare size={32}/></span><h3>{wrongChat?'Este enlace corresponde a un chat que ya terminó.':'Un chat para avanzar esta semana'}</h3><p>Habla con el equipo interno del proyecto, comparte archivos y resuelve pendientes. El chat y su contenido se eliminan automáticamente siete días después de abrirlo.</p><div><span><UsersRound size={17}/>Equipo del proyecto</span><span><Paperclip size={17}/>Archivos de hasta 10 MB</span><span><Clock3 size={17}/>Vigencia de siete días</span></div>{wrongChat?<Button variant="primary" onClick={()=>{const next=new URLSearchParams(params);next.set('chat',chatId!);setParams(next,{replace:true});}}>Ir al chat actual</Button>:context.data?.canCreate?<Button variant="primary" icon={<Plus size={17}/>} onClick={()=>{setError('');setConfirm({kind:'start'});}}>Abrir chat por siete días</Button>:<p className="chat-read-only">Pide a coordinación que abra el chat de este proyecto.</p>}</div>:<div className="project-chat-layout"><div className="chat-main"><div className="chat-status"><span className={connectionState==='live'?'connected':''}><i/>{connectionState==='live'?'Conectado · mensajes en tiempo real':'Reconectando las actualizaciones…'}</span><small>Solo equipo interno</small></div>
    <div ref={feed} className="chat-feed" role="log" aria-live="polite" aria-relevant="additions" aria-label="Chat del proyecto" onScroll={event=>{const element=event.currentTarget;const close=element.scrollHeight-element.scrollTop-element.clientHeight<100;setNearBottom(close);if(close)setIncoming(0);}}>
      {messagesQuery.hasNextPage&&<Button className="chat-load-older" size="sm" disabled={messagesQuery.isFetchingNextPage} onClick={async()=>{const element=feed.current;const height=element?.scrollHeight??0;await messagesQuery.fetchNextPage();requestAnimationFrame(()=>{if(element)element.scrollTop=element.scrollHeight-height;});}}>{messagesQuery.isFetchingNextPage?'Cargando…':'Ver mensajes anteriores'}</Button>}
      {messagesQuery.isLoading&&<p className="chat-loading">Cargando mensajes…</p>}{!messagesQuery.isLoading&&!messages.length&&<div className="chat-empty"><MessageSquare size={27}/><h3>Empieza la conversación</h3><p>Comparte qué necesitas resolver. Puedes adjuntar documentos o arrastrarlos aquí.</p></div>}
      {messages.map((message,index)=><div key={message.id}>{(!index||new Date(messages[index-1].createdAt).toLocaleDateString()!==new Date(message.createdAt).toLocaleDateString())&&<p className="chat-day-divider"><span>{new Date(message.createdAt).toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long'})}</span></p>}<article className={`chat-message ${message.user.id===currentUserId?'mine':''} ${message.deletedAt?'deleted':''}`}><span className="person-avatar">{initials(message.user.name)}</span><div className="chat-bubble"><header><strong>{message.user.id===currentUserId?'Tú':message.user.name}</strong><time dateTime={message.createdAt}>{new Date(message.createdAt).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}</time>{message.canDelete&&context.data?.canWrite&&<button title="Eliminar mensaje" aria-label={`Eliminar mensaje de ${message.user.name}`} disabled={busy} onClick={()=>{setError('');setConfirm({kind:'message',id:message.id});}}><Trash2 size={13}/></button>}</header>{message.deletedAt?<p className="chat-deleted">Mensaje eliminado</p>:<>{message.body&&<p>{message.body}</p>}{message.files.map(file=><div className="chat-file" key={file.id}><button className="chat-file-download" disabled={downloading===file.id} onClick={()=>void download(file)}><File size={20}/><span><strong>{file.name}</strong><small>{sizeLabel(file.size)} · Descargar</small></span>{downloading===file.id?<LoaderCircle size={15} className="chat-spinner"/>:<Download size={15}/>}</button>{context.data?.canWrite&&(file.uploadedById===currentUserId||context.data.canModerate)&&<button className="chat-file-delete" aria-label={`Eliminar ${file.name}`} disabled={busy} onClick={()=>{setError('');setConfirm({kind:'file',id:file.id,name:file.name});}}><X size={13}/></button>}</div>)}</>}</div></article></div>)}
    </div>{incoming>0&&<button className="chat-new-messages" onClick={()=>{if(feed.current)feed.current.scrollTo({top:feed.current.scrollHeight,behavior:'smooth'});setIncoming(0);}}><ArrowDown size={15}/>{incoming} mensajes nuevos</button>}
    {context.data?.canWrite?<form className="chat-compose" onSubmit={event=>{event.preventDefault();void send();}}><div className="chat-picked-files">{files.map(selected=><span key={selected.id}><File size={16}/><span><strong>{selected.file.name}</strong><small>{sizeLabel(selected.file.size)} · {selected.state==='uploading'?'Subiendo…':selected.state==='ready'?'Listo para enviar':selected.state==='error'?'No se pudo subir':'Preparado'}</small></span>{selected.state==='uploading'?<LoaderCircle size={15} className="chat-spinner"/>:<button type="button" aria-label={`Quitar ${selected.file.name}`} disabled={busy||Boolean(pending.current)} onClick={()=>void removePicked(selected.id)}><X size={14}/></button>}</span>)}</div><textarea rows={2} aria-label="Mensaje para el chat" placeholder="Escribe al equipo…" maxLength={10000} value={body} disabled={busy||Boolean(pending.current)} onChange={event=>setBody(event.target.value)} onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();void send();}}}/><footer><input ref={fileInput} type="file" multiple hidden onChange={(event:ChangeEvent<HTMLInputElement>)=>{pick(Array.from(event.target.files??[]));event.target.value='';}}/><Button variant="ghost" size="sm" icon={<Paperclip size={17}/>} disabled={busy||Boolean(pending.current)||files.length>=3} onClick={()=>fileInput.current?.click()}>Adjuntar</Button><small>Máx. 3 archivos · 10 MB cada uno</small><Button variant="primary" type="submit" icon={busy?<LoaderCircle size={16} className="chat-spinner"/>:<Send size={16}/>} disabled={busy||(!body.trim()&&!files.length)}>{busy?'Enviando…':pending.current?'Reintentar envío':'Enviar'}</Button></footer>{pending.current&&!busy&&<p className="chat-retry-note">El envío no se confirmó. Reintenta: el mensaje no se duplicará. <button type="button" onClick={()=>{pending.current=undefined;setBody('');files.forEach(file=>void removePicked(file.id));setFiles([]);setError('');}}>Descartar borrador</button></p>}</form>:<div className="chat-read-only"><ShieldCheck size={16}/>Tu rol permite leer esta conversación.</div>}
  </div><aside className="chat-side"><h3><UsersRound size={17}/>Equipo del proyecto</h3><div>{context.data?.participants.map(person=><span key={person.id}><b className="person-avatar">{initials(person.name)}</b><strong>{person.name}{person.id===currentUserId&&<small> Tú</small>}</strong></span>)}</div><p>Acceso interno del proyecto. Los responsables con acceso al proyecto también pueden consultar el chat.</p><section><Clock3 size={20}/><h3>Este espacio es temporal</h3><p>Mensajes y archivos dejarán de estar disponibles el <strong>{new Date(chat!.expiresAt).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})}</strong>.</p><p>Guarda los acuerdos permanentes en una tarea antes de esa fecha.</p></section></aside></div>}
  {confirm&&<Dialog title={confirm.kind==='start'?'Abrir chat por siete días':confirm.kind==='close'?'Cerrar y eliminar el chat':confirm.kind==='file'?'Eliminar archivo':'Eliminar mensaje'} description={confirm.kind==='start'?'Participará el equipo interno con acceso a este proyecto.':undefined} busy={busy} onClose={()=>{setConfirm(undefined);setError('');}}><div className="product-form"><p>{confirm.kind==='start'?'El chat comienza ahora y vence dentro de siete días. Al vencer se eliminarán los mensajes y archivos.':confirm.kind==='close'?'Se eliminarán los mensajes y todos los archivos de este chat para las personas del proyecto. Esta acción no se puede deshacer.':confirm.kind==='file'?`«${confirm.name}» dejará de estar disponible para el equipo. Esta acción no se puede deshacer.`:'El mensaje y sus archivos se eliminarán para el equipo. Quedará la indicación «Mensaje eliminado».'}</p>{error&&<p className="form-error" role="alert">{error}</p>}<footer className="product-form-actions"><Button disabled={busy} onClick={()=>setConfirm(undefined)}>Cancelar</Button><Button variant={confirm.kind==='start'?'primary':'danger'} disabled={busy} onClick={()=>void executeConfirm()}>{busy?'Guardando…':confirm.kind==='start'?'Abrir chat':confirm.kind==='close'?'Cerrar y eliminar':'Eliminar'}</Button></footer></div></Dialog>}
 </section>;
}
