import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, Circle, FolderKanban, Inbox, Plus, Search } from 'lucide-react';
import { apiRequest } from '../api/http';
import { formatDate } from '../lib/format';
import { Button, EmptyState, LoadingState } from './ui';
type WorkItem = { id: string; projectId: string; title: string; priority: string; dueAt?: string; completedAt?: string; progress: number; status: { name: string; color: string; category: string }; project: { id: string; name: string; color?: string }; assignees: { user: { id: string; name: string } }[] };
type WorkItems = { tasks: WorkItem[]; total: number; page: number; pages: number; summary: {total: number; today: number; overdue: number}; projects: { id: string; name: string }[] };
export function WorkItemsView({ token, workspaceId, completed = false, userName, unreadCount, onOpen, onProjects, onInbox, onCreate }: {
  token: string; workspaceId: string; completed?: boolean; userName: string; unreadCount: number; onOpen: (projectId: string, taskId: string) => void; onProjects: () => void; onInbox: () => void; onCreate?: () => void;
}) {
  const [search, setSearch] = useState(''); const [debounced, setDebounced] = useState('');
  const [focus, setFocus] = useState(''); const [projectId, setProjectId] = useState('');
  const [page, setPage] = useState(1);
  useEffect(() => { const timer = window.setTimeout(() => { setDebounced(search.trim()); setPage(1); }, 250); return () => window.clearTimeout(timer); }, [search]);
  const today = new Date(); today.setHours(0,0,0,0); const tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate()+1);
  const params = new URLSearchParams({state:completed?'completed':'active',mine:completed?'false':'true',page:String(page),search:debounced,today:today.toISOString(),tomorrow:tomorrow.toISOString()});
  if(focus) params.set('focus',focus); if(projectId) params.set('projectId',projectId);
  const query = useQuery({queryKey:['work-items',workspaceId,params.toString()],queryFn:()=>apiRequest<WorkItems>(`/workspaces/${workspaceId}/work-items?${params}`,{token})});
  useEffect(()=>{if(query.data && page>query.data.pages)setPage(query.data.pages);},[query.data,page]);
  const data = query.data;
  return <section className="day-home">
    <header className="day-home-heading"><div><p className="day-kicker">{completed?'Historial de proyectos':new Date().toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long'})}</p><h1>{completed?'El trabajo que ya lograron':`Tu día, ${userName.split(' ')[0]}.`}</h1><p>{completed?'Tareas terminadas, con su contexto y su historial.':'Un lugar para saber qué sigue y ponerte en marcha.'}</p></div>{onCreate&&!completed&&<Button variant="primary" icon={<Plus size={18}/>} onClick={onCreate}>Crear una tarea</Button>}</header>
    {!completed&&<div className="day-overview"><button className={`day-focus-card ${focus===''?'selected':''}`} onClick={()=>{setFocus('');setPage(1);}}><span><Circle size={18}/>Mis pendientes</span><strong>{data?.summary?.total??'—'}</strong><small>Todo lo que tienes por hacer<ArrowRight size={17}/></small></button><button className={`day-focus-card ${focus==='today'?'selected':''}`} onClick={()=>{setFocus('today');setPage(1);}}><span><CalendarDays size={18}/>Para hoy</span><strong>{data?.summary?.today??'—'}</strong><small>Entrega durante el día<ArrowRight size={17}/></small></button><button className={`day-focus-card ${focus==='overdue'?'selected':''}`} onClick={()=>{setFocus('overdue');setPage(1);}}><span><span className="day-attention-dot"/>Necesitan atención</span><strong>{data?.summary?.overdue??'—'}</strong><small>Tareas con fecha vencida<ArrowRight size={17}/></small></button></div>}
    <div className={`day-home-grid ${completed?'full':''}`}><section className="day-work-panel"><header><div><h2>{completed?'Terminadas':focus==='today'?'Tu agenda de hoy':focus==='overdue'?'Recupera estos pendientes':'Lo que sigue'}</h2><span>{data ? `${data.total} tareas`:'Cargando…'}</span></div><label className="day-search"><Search size={16}/><input aria-label="Buscar tareas" placeholder="Buscar tarea…" value={search} onChange={event=>setSearch(event.target.value)}/></label></header>
    <div className="day-work-filter"><select aria-label="Filtrar proyecto" value={projectId} onChange={event=>{setProjectId(event.target.value);setPage(1);}}><option value="">Todos mis proyectos</option>{data?.projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select><span>{completed?'Fecha de cierre':'Ordenadas por entrega'}</span></div>
    {query.isLoading&&<LoadingState label="Cargando tu trabajo…" rows={4}/>}{query.error&&<p className="form-error" role="alert">{query.error.message}<Button onClick={()=>void query.refetch()}>Reintentar</Button></p>}
    <div className="day-agenda">{data?.tasks.map(task=><button key={task.id} className="day-agenda-task" onClick={()=>onOpen(task.projectId,task.id)}><span className={`day-agenda-check ${completed?'done':''}`}>{completed&&<Check size={14}/>}</span><span className="day-agenda-title"><strong>{task.title}</strong><small><i style={{background:task.project.color??'#416553'}}/>{task.project.name}{completed&&` · ${task.assignees.map(person=>person.user.name).join(', ')||'Sin responsable'}`}</small></span><span className="day-agenda-status"><i style={{background:task.status.color}}/>{task.status.name}</span><span className={`day-agenda-date ${!completed&&task.dueAt&&new Date(task.dueAt)<today?'late':''}`}>{formatDate(completed?task.completedAt:task.dueAt)}</span><ChevronRight size={16}/></button>)}</div>
    {data?.total===0&&<EmptyState icon={<Check size={26}/>} title={search||projectId?'No encontramos tareas':focus==='overdue'?'No tienes tareas vencidas':focus==='today'?'Hoy no tienes entregas':completed?'Aquí aparecerán las tareas terminadas':'Tu agenda está libre'} description={search||projectId?'Cambia la búsqueda o el proyecto.':completed?'Al cerrar una tarea se conservará aquí.':'Las tareas que te asignen aparecerán aquí automáticamente.'} action={onCreate&&!completed?<Button onClick={onCreate} icon={<Plus size={16}/>}>Crear tarea</Button>:undefined}/>}
    {data&&data.total>0&&<footer className="day-list-pagination"><span>{(page-1)*25+1}–{Math.min(page*25,data.total)} de {data.total}</span><div><Button size="sm" aria-label="Página anterior" disabled={page<=1||query.isFetching} onClick={()=>setPage(page-1)}><ChevronLeft size={16}/></Button><Button size="sm" aria-label="Página siguiente" disabled={page>=data.pages||query.isFetching} onClick={()=>setPage(page+1)}><ChevronRight size={16}/></Button></div></footer>}
    </section>{!completed&&<aside className="day-home-aside"><button className="day-inbox-card" onClick={onInbox}><Inbox size={24}/><strong>{unreadCount?`${unreadCount} novedades para ti`:'Estás al día'}</strong><p>{unreadCount?'Asignaciones, respuestas y cambios de tu equipo.':'Tus avisos llegarán aquí en cuanto sucedan.'}</p><span>Abrir mi bandeja<ArrowRight size={16}/></span></button><section className="day-project-shortcuts"><header><h2>Mis proyectos</h2><FolderKanban size={18}/></header>{data?.projects.slice(0,5).map(project=><button key={project.id} onClick={()=>{setProjectId(project.id);setPage(1);setFocus('');}}><span>{project.name.slice(0,1).toUpperCase()}</span><strong>{project.name}</strong><ChevronRight size={15}/></button>)}<button className="day-all-projects" onClick={onProjects}>Ver todos los proyectos<ArrowRight size={16}/></button></section></aside>}</div>
  </section>;
}
